//SHEILa========================================================================
// Name        : language.inc
// Author      : FlowerGenius<justanortherngirl58@gmail.com>
// Version     : 
// Copyright   : 
// Description : 
// Module      : SHEILa
// Created     : Apr 12, 2018
// Modified    :
//==============================================================================

#ifndef CPP_LANGUAGE_INC_
#define CPP_LANGUAGE_INC_

//#include "CppMemberFunction/CppMemberFunction.h"
//
//#include "CppTypeDefinition/CppTypeDefinition.h"
//
//#include "CppConstructor/CppConstructor.h"
//
//#include "CppDataMember/CppDataMember.h"
//
//#include "CppDestructor/CppDestructor.h"
//
//#include "CppClass/CppClass.h"
//
//#include "CppMacro/CppMacro.h"
//
//#include "CppVariable/CppVariable.h"
//
//#include "CppFunction/CppFunction.h"
//
//#include "CppPPDirective/CppPPDirective.h"
//
//#include "CppHeader/CppHeader.h"
//
//#include "CppSource/CppSource.h"
//
//#include "CppFile/CppFile.h"
//
//#include "CppObject/CppObject.h"

#include "Cpp.h"
#include "CppCompiler/CppCompiler.h"


#endif /* CPP_LANGUAGE_INC_ */
