//SHEILa======================================================================
// Name        : includes.inc
// Author      : erin
// Version     : 
// Copyright   : 
// Description : 
// Module	   : SHEILa
// Created     : Apr 2, 2018
// Modified    :
//============================================================================

#ifndef INCLUDES_INC_
#define INCLUDES_INC_

#include "Entity/Emotion/Emotion.hpp"
#include "Entity/Entity.hpp"
#include "Entity/Feeling/Feeling.hpp"
#include "Entity/IPAddress/IPAddress.hpp"
#include "Entity/IPAddress/IPAddress.hpp"
#include "Entity/Language/Language.hpp"
#include "Entity/Mood/Mood.hpp"
#include "Entity/Network/Network.hpp"
#include "Entity/OperatingSystem/OperatingSystem.hpp"

#include "Entity/Platform/Platform.hpp"

#include "Entity/Processor/Processor.h"


#include "Entity/Range/Range.hpp"

#include "Entity/Runtime/Runtime.hpp"
#include "Entity/Server/Server.hpp"

#include "Entity/SHEILaCoreServer/SHEILaCoreServer.hpp"

#include "Entity/Version/Version.hpp"

#endif /* INCLUDES_INC_ */


