//SHEILa======================================================================
// Name        : includes.inc
// Author      : erin
// Version     : 
// Copyright   : 
// Description : 
// Module	   : SHEILa
// Created     : Apr 2, 2018
// Modified    :
//============================================================================

#ifndef INCLUDES_INC_
#define INCLUDES_INC_

#include <Entity/Entity.h>

#include <Entity/Emotion/Emotion.h>

#include <Entity/Feeling/Feeling.h>

#include <Entity/IPAddress/IPAddress.h>
#include <Entity/IPv4/IPv4.h>
#include <Entity/IPv6/IPv6.h>

#include <Entity/Language/Language.h>
#include <Entity/Mood/Mood.h>

#include <Entity/Network/Network.h>

#include <Entity/OS/OS.h>

#include <Entity/Platform/Platform.h>

#include <Entity/Processor/Processor.h>


#include <Entity/Range/Range.h>

#include <Entity/Runtime/Runtime.h>

#include <Entity/Server/Server.h>
#include <Entity/SHEILaCoreServer/SHEILaCoreServer.h>

#include <Entity/Version/Version.h>

#endif /* INCLUDES_INC_ */


