//SHEILa======================================================================
// Name        : symbols.inc
// Author      : erin
// Version     : 
// Copyright   : 
// Description : 
// Module	   : SHEILa
// Created     : Mar 31, 2018
// Modified    :
//============================================================================

#ifndef SYMBOLS_INC_
#define SYMBOLS_INC_

#define MIN_PERCENTAGE -100.0L
#define MAX_PERCENTAGE  100.0L

/* The location on the server of my core files */
#define SHEILA_WORKSPACE_DIR "/home/erin/Documents/SHEILa"

/* The location on the server of my memory storage */
#define SHEILA_MEM_DIR "/home/erin/Docuemnts/SHEILa/mem"

/* The maximuim line size in a source file */
#define SHEILA_LINE_MAX 80

//#define SHEILA_SRC_DIR SHEILA_WORKSPACE_DIR "/SHEILa/src"
//
//#define SHEILA_DEBUG_DIR SHEILA_WORKSPACE_DIR "/SHEILa/Debug"
//
//#define SHEILA_RELEASE_DIR SHEILA_WORKSPACE_DIR "/SHEILa/Release"
//
//
//#define SHEILA_runtime_SRC_DIR SHEILA_WORKSPACE_DIR "/SHEILa_runtime/src"
//
//#define SHEILA_runtime_DEBUG_DIR SHEILA_WORKSPACE_DIR "/SHEILa_runtime/Debug"
//
//#define SHEILA_runtime_RELEASE_DIR SHEILA_WORKSPACE_DIR "/SHEILa_runtime/Release"
//
//
//#define SHEILA_daemon_SRC_DIR SHEILA_WORKSPACE_DIR "/SHEILa_daemon/src"
//
//#define SHEILA_daemon_DEBUG_DIR SHEILA_WORKSPACE_DIR "/SHEILa_daemon/Debug"
//
//#define SHEILA_daemon_RELEASE_DIR SHEILA_WORKSPACE_DIR "/SHEILa_daemon/Release"



#endif /* SYMBOLS_INC_ */
