var searchData=
[
  ['feeling',['Feeling',['../classsheila_1_1Feeling.html#afe5fbdef9a559ced1c65c6ddf0224eed',1,'sheila::Feeling::Feeling()'],['../classsheila_1_1Feeling.html#a47a46fc7586bd1061d16317d6c7c1bd1',1,'sheila::Feeling::Feeling(std::string name, std::string desc, long double ang_low, long double ang_hi, long double dis_low, long double dis_hi, long double sad_low, long double sad_hi, long double sur_low, long double sur_hi, long double fea_low, long double fea_hi, long double tru_low, long double tru_hi, long double joy_low, long double joy_hi, long double ant_low, long double ant_hi, long double min_diff_ang_dis, long double max_diff_ang_dis, long double min_diff_ang_sad, long double max_diff_ang_sad, long double min_diff_ang_sur, long double max_diff_ang_sur, long double min_diff_ang_fea, long double max_diff_ang_fea, long double min_diff_ang_tru, long double max_diff_ang_tru, long double min_diff_ang_joy, long double max_diff_ang_joy, long double min_diff_ang_ant, long double max_diff_ang_ant, long double min_diff_dis_sad, long double max_diff_dis_sad, long double min_diff_dis_sur, long double max_diff_dis_sur, long double min_diff_dis_fea, long double max_diff_dis_fea, long double min_diff_dis_tru, long double max_diff_dis_tru, long double min_diff_dis_joy, long double max_diff_dis_joy, long double min_diff_dis_ant, long double max_diff_dis_ant, long double min_diff_sad_sur, long double max_diff_sad_sur, long double min_diff_sad_fea, long double max_diff_sad_fea, long double min_diff_sad_tru, long double max_diff_sad_tru, long double min_diff_sad_joy, long double max_diff_sad_joy, long double min_diff_sad_ant, long double max_diff_sad_ant, long double min_diff_sur_fea, long double max_diff_sur_fea, long double min_diff_sur_tru, long double max_diff_sur_tru, long double min_diff_sur_joy, long double max_diff_sur_joy, long double min_diff_sur_ant, long double max_diff_sur_ant, long double min_diff_fea_tru, long double max_diff_fea_tru, long double min_diff_fea_joy, long double max_diff_fea_joy, long double min_diff_fea_ant, long double max_diff_fea_ant, long double min_diff_tru_joy, long double max_diff_tru_joy, long double min_diff_tru_ant, long double max_diff_tru_ant, long double min_diff_joy_ant, long double max_diff_joy_ant)']]],
  ['feelings',['feelings',['../classsheila_1_1SHEILaCoreServer.html#a56daf9a54f3cbde45029374dd7a96906',1,'sheila::SHEILaCoreServer']]],
  ['find_5factive_5fruntimes',['find_active_runtimes',['../namespacesheila_1_1platform.html#a84f714b22daab73c2626e675cad591f5',1,'sheila::platform']]],
  ['find_5faudio_5finput_5fdevices',['find_audio_input_devices',['../namespacesheila_1_1platform.html#a3881ef3931b84c6d82823fc8f51278b0',1,'sheila::platform']]],
  ['find_5faudio_5foutput_5fdevices',['find_audio_output_devices',['../namespacesheila_1_1platform.html#a8b10766c0a27194b17ffc910ed25e565',1,'sheila::platform']]],
  ['find_5ftext_5finput_5fdevices',['find_text_input_devices',['../namespacesheila_1_1platform.html#a4ce06715a3c9c5fb95d773fa920df208',1,'sheila::platform']]],
  ['find_5ftext_5foutput_5fdevices',['find_text_output_devices',['../namespacesheila_1_1platform.html#a1fb88175c1d8e5f4ec8f79cdccbfcb64',1,'sheila::platform']]],
  ['find_5fvideo_5finput_5fdevices',['find_video_input_devices',['../namespacesheila_1_1platform.html#ab58932a6cce88d74da30adb231359baf',1,'sheila::platform']]],
  ['find_5fvideo_5foutput_5fdevices',['find_video_output_devices',['../namespacesheila_1_1platform.html#ae39ca8539cef9a5ad596664be44089dc',1,'sheila::platform']]],
  ['fundamentaltype',['fundamentalType',['../classsheila_1_1cpp_1_1Cpp.html#a4ffaf48f70961a502402495ed33759b7',1,'sheila::cpp::Cpp']]]
];
