//SHEILa========================================================================
// Name        : language.inc
// Author      : FlowerGenius<justanortherngirl58@gmail.com>
// Version     : 
// Copyright   : 
// Description : 
// Module      : SHEILa
// Created     : Apr 12, 2018
// Modified    :
//==============================================================================

#ifndef C_LANGUAGE_INC_
#define C_LANGUAGE_INC_

//#include "C.h"

#include "CHeaderFile/CHeaderFile.h"



#endif /* C_LANGUAGE_INC_ */
