//SHEILa========================================================================
// Name        : language.inc
// Author      : FlowerGenius<justanortherngirl58@gmail.com>
// Version     : 
// Copyright   : 
// Description : 
// Module      : SHEILa
// Created     : Apr 12, 2018
// Modified    :
//==============================================================================

#ifndef CPP_LANGUAGE_INC_
#define CPP_LANGUAGE_INC_

#include "Cpp.h"

#include "CppClass/CppClass.h"

#include "CppCompiler/CppCompiler.h"

#include "CppConstructor/CppConstructor.h"

#include "CppDataMember/CppDataMember.h"

#include "CppDestructor/CppDestructor.h"

#include "CppFunction/CppFunction.h"

#include "CppHeaderFile/CppHeaderFile.h"

#include "CppMacro/CppMacro.h"

#include "CppMemberFunction/CppMemberFunction.h"

#include "CppSourceFile/CppSourceFile.h"

#include "CppSymbol/CppSymbol.h"

#include "CppVariable/CppVariable.h"

#endif /* CPP_LANGUAGE_INC_ */
